### ISSUE TITLE
Adding a note in offline mode fails with "no connection"

### ISSUE THREAD

**Issue by michaelkarrer81** [Odoo-mobile/messaging#10]
This may be on purpose but i really think that it should be possible to write notes offline - if i can not add any information offline the whole app seems a little useless. May be a harsh opinion but probably a valid one.

**Comment by dpr-odoo** [comment]
We are working on it and will available soon.

**Comment by h4k1m0u** [comment]
Do you plan to sync server with client on network tick?  
I mean a mobile client can send a message offline, but this message is stored on local sqlite db, and isnt sent until an internet connection is established.

**Comment by dpr-odoo** [comment]
Hello @michaelkarrer81 
New app updated with Offline support in Notes. You can download it from PlayStore.
https://play.google.com/store/apps/details?id=com.odoo.notes
Git Project : https://github.com/Odoo-mobile/notes

@h4k1m0u 
Also Messaging app updated for offline support. Your mail will stored in outbox if your device is not in network. Here is new app (v2.0) : https://play.google.com/store/apps/details?id=com.odoo

Regards,
dpr
