### ISSUE TITLE
New Messages Counter most of the time wrong?

### ISSUE THREAD

**Issue by michaelkarrer81** [Odoo-mobile/messaging#11]
From time to time i get a system notification from the odoo app on my xperia Z1 telling me  that there are a number of new messages available: 

If i klick on the notification it takes me to Odoo App / Inbox BUT there, most of the time, are NO new Messages or the number of new Messages shown earlier in the notification has nothing to do with the number of messages in the Odoo / Inbox ?!?

**Comment by dpr-odoo** [comment]
Hello,
New update with fix published on play store. Available soon.

**Comment by michaelkarrer81** [comment]
Still not available in Austria ;) - Can't Wait to test! Keep up the spirit and the good work. Framework V2 looks very promising!
