### ISSUE TITLE
Issue to connect to Odoo server

### ISSUE THREAD

**Issue by Da3mi** [Odoo-mobile/messaging#12]
i've created my odoo server via this website : https://www.odoo.com/page/start .
and when i tried to connect from my virtual mobile, it didn't work .

Can anyone help me plz

**Comment by dpr-odoo** [comment]
Hello,

Currently messaging app does not support **Odoo Instance login**, which you have created from odoo.com.

Login support for odoo instance will available soon..
Regards,
