### ISSUE TITLE
Cant coonect

### ISSUE THREAD

**Issue by eventsis** [Odoo-mobile/messaging#27]
I Have created two VPS on AWS Cloud.
1. Bitnami click and play: Initially had no database erors and managed to get fixed but now it says invlaid username or password
2. My own build using port 8069: This will only login as admin if i try any other user it fails as says invalid username or password as above

Is this a permissions thing in odoo??

If so what specifically is it? or is there a command i need tun via ssh?

**Comment by dpr-odoo** [comment]
Hello,

This issue may be because of your Odoo server is hosted on Apache Web Server as previous issue #15

We will update you when this issue resolved.

Regards,
Dharmang Soni

**Comment by eventsis** [comment]
Apache was not installed unless aws has it preconfigured as such. I installed ngix and it came up saying welcome to ngix on port 80 but even after putting the rules iin it would only ever show that page.

Would you advise it best to have a fixed IP and build a server from scratch?

Thanks for getting back to me.

Kind Regards

Scott Nolan

**Comment by dpr-odoo** [comment]
Hello,

Issue has been fixed Odoo-mobile/framework@badd412. Update available soon on playstore.
