### ISSUE TITLE
Unable to reach Odoo server

### ISSUE THREAD

**Issue by cutech** [Odoo-mobile/messaging#28]
I'm using SISalp's online Odoo offering and receive the error Unable to reach Odoo Server. Odoo Mobile works fine with a test server that points to port 8069. I've tried with and without http:// and ports 80 and 8069. When I use 8069/80 it seeks (shows the spinning icon) continuously. (My url does have the - character twice in it: odoo.c-u-tech.com)

**Comment by dpr-odoo** [comment]
Hello,

This issue may be because of your Odoo server is hosted on Apache Web Server as previous issue https://github.com/Odoo-mobile/messaging/issues/15 

We will update you when this issue resolved.

Regards,
Dharmang Soni

**Comment by dpr-odoo** [comment]
Hello,

Issue has been fixed Odoo-mobile/framework@badd412. Update available soon on playstore.
