### ISSUE TITLE
Odoo Server URL: Unable to reach the Odoo Server

### ISSUE THREAD

**Issue by ghost** [Odoo-mobile/messaging#3]
I just installed the Odoo Mobile app on my Android phone and typed my Odoo Server URL xxxxxxxxxx.odoo.com and got the error "Unable to reach the Odoo Server". What is the correct URL syntax?

**Comment by dpr-odoo** [comment]
Hello,

Issue for Odoo server connection through Odoo Moble application has been solved. New APK update will available soon.

Thanks,
Dharmang Soni (dpr)

**Comment by szikar** [comment]
Today I installed the client on Google Play store and produced this error.

**Comment by connerk** [comment]
I'm also getting this error.

**Comment by samemotion** [comment]
I also get the same error.

**Comment by johannesfasching** [comment]
also get this error...

**Comment by dpr-odoo** [comment]
Hello,

If you have Odoo Instance, Please refer this document to login with your Odoo instances.

https://dharmangsoni.odoo.com/blogpost/login-with-odoo-saas-account-in-odoo-mobile-2/

Regards,
