### ISSUE TITLE
odoo mobile stuck on creating account

### ISSUE THREAD

**Issue by Jayuda** [Odoo-mobile/messaging#35]
Hello guys,
i have error at create account on my own host server.
The output error : 

05-27 11:37:41.285     789-1779/com.odoo E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
05-27 11:37:41.285     789-1779/com.odoo W/System.err﹕ java.lang.RuntimeException: android.os.TransactionTooLargeException
05-27 11:37:41.295     789-1779/com.odoo W/System.err﹕ at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:568)
05-27 11:37:41.335     789-1779/com.odoo W/System.err﹕ at com.odoo.auth.OdooAccountManager.createAccount(OdooAccountManager.java:104)
05-27 11:37:41.335     789-1779/com.odoo W/System.err﹕ at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:252)
05-27 11:37:41.335     789-1779/com.odoo W/System.err﹕ at com.odoo.base.login_signup.AccountCreate$CreateAccount.doInBackground(AccountCreate.java:225)
05-27 11:37:41.345     789-1779/com.odoo W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-27 11:37:41.345     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
05-27 11:37:41.375     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:137)
05-27 11:37:41.395     789-1779/com.odoo W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
05-27 11:37:41.395     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
05-27 11:37:41.425     789-1779/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
05-27 11:37:41.435     789-1779/com.odoo W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
05-27 11:37:41.435     789-1779/com.odoo W/System.err﹕ Caused by: android.os.TransactionTooLargeException
05-27 11:37:41.445     789-1779/com.odoo W/System.err﹕ at android.os.BinderProxy.transact(Native Method)
05-27 11:37:41.445     789-1779/com.odoo W/System.err﹕ at android.accounts.IAccountManager$Stub$Proxy.addAccount(IAccountManager.java:579)
05-27 11:37:41.485     789-1779/com.odoo W/System.err﹕ at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:565)
05-27 11:37:41.485     789-1779/com.odoo W/System.err﹕ ... 10 more
05-27 11:37:46.545     789-1195/com.odoo W/System.err﹕ java.io.IOException: SERVICE_NOT_AVAILABLE
05-27 11:37:46.545     789-1195/com.odoo W/System.err﹕ at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
05-27 11:37:46.545     789-1195/com.odoo W/System.err﹕ at odoo.OdooMobile$1.doInBackground(OdooMobile.java:40)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at odoo.OdooMobile$1.doInBackground(OdooMobile.java:1)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:137)
05-27 11:37:46.554     789-1195/com.odoo W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
05-27 11:37:46.565     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
05-27 11:37:46.565     789-1195/com.odoo W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
05-27 11:37:46.565     789-1195/com.odoo W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
05-27 11:38:00.064      789-789/com.odoo I/Choreographer﹕ Skipped 35 frames!  The application may be doing too much work on its main thread.
05-27 11:39:15.515      789-789/com.odoo I/Choreographer﹕ Skipped 36 frames!  The application may be doing too much work on its main thread.
05-27 11:39:16.144      789-789/com.odoo I/Choreographer﹕ Skipped 38 frames!  The application may be doing too much work on its main thread.
05-27 11:39:17.445      789-789/com.odoo I/Choreographer﹕ Skipped 78 frames!  The application may be doing too much work on its main thread.
05-27 11:39:17.804      789-789/com.odoo I/Choreographer﹕ Skipped 93 frames!  The application may be doing too much work on its main thread.
05-27 11:39:18.194      789-789/com.odoo I/Choreographer﹕ Skipped 61 frames!  The application may be doing too much work on its main thread.
05-27 11:39:18.525      789-789/com.odoo I/Choreographer﹕ Skipped 83 frames!  The application may be doing too much work on its main thread.

any other programmers have a solutions ?
thanks

**Comment by AsKaeternam** [comment]
Is someone have a solution for this problem ?
