### ISSUE TITLE
Connection to server OK, but can't use OpenERP/Odoo account

### ISSUE THREAD

**Issue by ThierryMallard** [Odoo-mobile/messaging#5]
I have a OpenERP (Odoo) instance on my company's server.
On this server, I'm connecting using an openerp account (SSO), which works fine on the Web.
For the Odoo mobile application, a local account works fine, but my OpenERP doesn't work. Can you tell me if this authentification is supposed to work (maybe not at this time), or if there's a specific syntax to use for such accounts ? (I just entered my e-mail as identifier).
Thanks !

**Comment by dpr-odoo** [comment]
Hello ThierryMallard,

Issue for Odoo server connection through Odoo Moble application has been solved. New APK update will available soon.

Process for connecting Odoo is as same as you connect on web.

Thanks,
Dharmang Soni (dpr)
