### ISSUE TITLE
Invalid Username or Password

### ISSUE THREAD

**Issue by ghost** [Odoo-mobile/messaging#6]
Odoo Server URL works now :+1: and I can select a database. But I get the error "Invalid Username or Password !" I have tried to connect to Odoo Online (Oauth login) and also OpenERP V7 On-Premise (not Oauth login).

**Comment by dpr-odoo** [comment]
Currently application does not support **Oauth Login**. You need system _username_ and _password_ to login with Mobile application.

**Comment by ghost** [comment]
I tried using system username and password on V7 On-Premise, and it didn't work.
On the Odoo Online SaaS I cannot set any system password because of the Oauth.
What can I do?

**Comment by ghost** [comment]
Did anyone successfully login to Odoo Mobile for Android?

**Comment by dpr-odoo** [comment]
Can you send us your Odoo server URL ? Because we are not facing any issue regarding login with V7

**Comment by dpr-odoo** [comment]
Hello @norlinhenrik 

New app is available with Odoo Oauth login support : https://play.google.com/store/apps/details?id=com.odoo

Refer this blog for more detail : https://dharmangsoni.odoo.com/blogpost/login-with-odoo-saas-account-in-odoo-mobile-2/

Regards,
dpr
